spring:
  profiles:
    active: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minimaltodo
    username: root
    password: ElTesoro@0258
    platform: mysql
    validationQuery: SELECT 1
    # hikari:
    #   maximumPoolSize: 3
    #   minimumIdle: 1
    #   connectionTestQuery: select * from information_schema.tables limit 1
    #   idleTimeout: 600000
    #   maxLifetime: 1800000
    #   poolName: PotatoPool
    #   connectionTimeout: 30000
  devtools:
    add-properties: false
  data.jdbc.repositories.enabled: false
  thymeleaf:
    check-template-location: false
  jpa:
    open-in-view: false
    show-sql: false
    # show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        # dialect: org.hibernate.dialect.MySQL8InnoDBDialect
        # dialect: org.hibernate.dialect.SQLServerDialect
        initialize: true
        format_sql: true
        
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs

logging:
  level:
    web: DEBUG
    # com.zaxxer.hikari: DEBUG

jwt:
  secret: potatoSalad

